name = "Modpack Vish"
author = "Felipe (flipeip)"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "modpack/index.toml"
hash-format = "sha256"
hash = "e817650140c7a1a58013fd7c716166395a52f64d7e6e345aa112b5890c3fd198"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"

[options]
meta-folder-base = "modpack"
