name = "Modpack Vix"
author = "Felipe (flipeip)"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5cb744f252a579f64893bb3e640414b6fa6fbf9ff0ea3ea8872750b4ae0f61ab"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
