name = "MineMod 2025"
author = "flipeip"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3449cff90bd88fbb3392e628196b84428d63928091c2550670d7c0317f91331d"

[versions]
minecraft = "1.21.1"
neoforge = "21.10.20-beta"

[options]
acceptable-game-versions = ["fabric"]
