name = "MineMod 2025"
author = "flipeip"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9ae8ac30ef820cc80d0ff47deed72a41033c2dca03db08b62af39c5d02cdbbe5"

[versions]
minecraft = "1.21.1"
neoforge = "21.10.20-beta"

[options]
acceptable-game-versions = ["fabric"]
