name = "Modpack Vix"
author = "Felipe (flipeip)"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8ac2960e27c2dd84e3e21550c933004e4ef70f60c2a81aa5f9e93919321c6fa1"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
