name = "MineMod 2025"
author = "flipeip"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d687170732b2fbb454c115892c50663db1e63c756d6b267957deac59a07899b6"

[versions]
minecraft = "1.21.1"
neoforge = "21.10.20-beta"

[options]
acceptable-game-versions = ["fabric"]
