name = "Modpack 2025"
author = "flipeip"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ddc0b8a722eb8a13b3c006e728f94ff4597b35f2d6d57e56e76349174ae3b0c9"

[versions]
minecraft = "1.21.1"
neoforge = "21.10.20-beta"

[options]
acceptable-game-versions = ["fabric"]
