name = "MineMod 2025"
author = "flipeip"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2d4b9fa7481f9421f8d1a31bf7241446cb9f895d0fde78b237f62b0b7dfdb0c7"

[versions]
minecraft = "1.21.1"
neoforge = "21.10.20-beta"

[options]
acceptable-game-versions = ["fabric"]
