name = "Modpack Vix"
author = "Felipe (flipeip)"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "61741f17b77ab3e58471c73af395ef7714af59c06d80a44f84a8409472ca09c4"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
