name = "Modpack Vix"
author = "Felipe (flipeip)"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "modpack/index.toml"
hash-format = "sha256"
hash = "483fdbe6acde6282464818faf3e1a652b6509c14ec28e82c2f6a37eef4293cfb"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"

[options]
meta-folder-base = "modpack"
